version: '3'

dotenv: ['.env']

tasks:
  upgrade:
    desc: Update all go dependencies
    cmds:
      #- cd golang-shared-libs && go get -u */**
      - cd input-reader && go get -u
      - cd item-store && go get -u
      - cd serial-writer && go get -u
      - cd test-gpio && go get -u
      - cd vdf-controller && go get -u
